version: '2'

services:
  data:
    image: busybox:latest
    hostname: data
    container_name: rehearsal-data
    volumes:
      - ../:/app
    entrypoint: tail -f /dev/null

  nginx:
    network_mode: host
    hostname: nginx
    image: nginx:alpine
    container_name: rehearsal-nginx
    volumes_from:
      - data
    volumes:
      - ./nginx/dev/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./data/nginx/:/var/log/nginx
    depends_on:
      - fpm
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - "TZ=Europe/Moscow"

  fpm:
    working_dir: /app
    hostname: php-fpm-rehearsals
    container_name: rehearsal-php
    build:
      context: ./php/
    volumes_from:
      - data
    volumes:
      - ./data/php/:/var/log/php7-fpm
      - ./php/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./php/cron/crontab.main:/crontab/crontab.main
      - ./php/app-config.ini:/usr/local/etc/php/conf.d/app-config.ini
      - /var/www
    depends_on:
      - db
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - "TZ=Asia/Yekaterinburg"

  db:
    image: postgres:latest
    container_name: rehearsal-db
    hostname: db
    volumes_from:
      - data
    volumes:
      #- ./docker/data/db_log:/var/log/mysql
      - ./data/db:/var/lib/mysql
      - ./db/default.dev.cnf:/etc/mysql/conf.d/default.cnf
    env_file:
      - database.env